### ISSUE TITLE
colorize the output

### ISSUE THREAD

**Issue by mzfr** [common-nighthawk/go-figure#11]
Is it possible to print colorful figures? If not do you plan to add this?

**Comment by common-nighthawk** [comment]
That's a nice idea!  PR here: https://github.com/common-nighthawk/go-figure/pull/12.  Let me know if this works.

**Comment by mzfr** [comment]
@common-nighthawk how do I pull the changes to my package? I mean I ran `go get -u github.com/common-nighthawk/go-figure` and then in my code I did the following:

```
myFigure := figure.NewFigure("# gtfo", "big", "green", true)
myFigure.Print()
```

And I am getting error:

```
./main.go:102:30: too many arguments in call to figure.NewFigure
        have (string, string, string, bool)
        want (string, string, bool)
```

**Comment by common-nighthawk** [comment]
You'll need to do--
```
myFigure := figure.NewColorFigure("# gtfo", "big", "green", true)
myFigure.Print()
```

Go doesn't support optional args well, and I didn't want to introduce a breaking change.  So you'll need to use the `NewColorFigure`.
