### ISSUE TITLE
Can I embed a font in binary?

### ISSUE THREAD

**Issue by qindj** [common-nighthawk/go-figure#3]
Hi, Author

I want to publish the binary exe file without the fonts folder, is that possible?

Thanks!

**Comment by common-nighthawk** [comment]
thanks for opening this issue!

sure--go for it. 😄 

im just curious, what is the reason for this?  i can think of two--
1. performance - so a text file doesnt need to be parsed for every print
2. cleaning up the file path - finding the file to parse is currently messy

how are you going to add the font to the binary and support all the font options.  does it make sense to include just the default font with an option for parsing the file when another font is selected?

if its easy to submit a PR than answer the questions, that works too!

**Comment by qindj** [comment]
thanks for your reply.

the second is the reason, the "fonts" folder would be marked as "useless" and deleted in some PC Manager software.

I think it's better to load font from resource first, using package such as https://github.com/jteeuwen/go-bindata , if it is failed, then check the fonts folder.

I'll submit a PR in a day or two

**Comment by sivachandran** [comment]
PR #4 has changes for reading embedded font.

**Comment by common-nighthawk** [comment]
wahoo!  thank you SO much for the PR.  i just started a new job, so i apologize about being so slow to review a small change.  i hope to get to it within the next few days.

**Comment by common-nighthawk** [comment]
The README has been updated with the change: https://github.com/common-nighthawk/go-figure/commit/2d3c686981b48f9d6022181dc810381325b16b24

Closing this issue 😄
