### ISSUE TITLE
Elite Font Support

### ISSUE THREAD

**Issue by KeyLo99** [common-nighthawk/go-figure#7]
Is there any chance for this project to support [Elite](http://patorjk.com/software/taag/#p=display&f=Elite&t=test%0A) font?

**Comment by common-nighthawk** [comment]
Sure.  Let me know if this looks okay: https://github.com/common-nighthawk/go-figure/pull/8

What are you using it for? :)

**Comment by KeyLo99** [comment]
> Sure. Let me know if this looks okay: #8
> 
> What are you using it for? :)

Yes it looks fine.
Using it for a [project](https://github.com/KeyLo99/God), elite font looks like ANSI art. So... :)
